### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by V3L0C1T13S** [ShadowLp174/revoice.js#9]
Typescript typings would be useful, since many bots use TS.

**Comment by ShadowLp174** [comment]
Well, I'd rather not switch to TypeScript...

I'm too lazy to write down some points so here a link: :)

https://dev.to/joelbonetr/comment/1gj3d

**Comment by itzTheMeow** [comment]
you forgot to return the media track in the streamTrack getter
Media.js:
![image](https://user-images.githubusercontent.com/50887230/195206413-9d551d53-3abb-406c-a637-676163b7afa8.png)

i'm converting this package to typescript, ts caught this issue and i was able to fix it
![image](https://user-images.githubusercontent.com/50887230/195206452-ad49a39a-1bdb-4bf3-a626-ccdf7d122a32.png)
![image](https://user-images.githubusercontent.com/50887230/195206471-0be2f7e6-091d-4de1-8cd6-77c378a5a908.png)

+1 for official typescript support

**Comment by itzTheMeow** [comment]
I've ported this project to typescript as `revoice-ts`: https://github.com/itzTheMeow/revoice.ts

**Comment by ShadowLp174** [comment]
I indeed forgot to return the mediastreamtrack. This isn't a problem though, as this getter isn't used anywhere... I probably wrote that some time at 3am

**Comment by ShadowLp174** [comment]
we got typings now thanks to @mezotv :)
